"""
Full Stack Development Agent
Builds complete websites and web applications
Supports: React, Vue, Angular, Next.js, FastAPI, Django,
Express, Laravel, Rails, Spring Boot, and more
"""

import os
import json
import re
from agents.base_agent import BaseAgent


FULLSTACK_SYSTEM = """You are an expert full stack developer with 20+ years of experience.
You build complete, production-ready web applications.
When asked to build a website or web app, you provide:
1. Complete frontend code (HTML/CSS/JS or React/Vue/Angular)
2. Complete backend code (FastAPI/Django/Express/etc)
3. Database schema (SQL or NoSQL)
4. Docker configuration
5. API documentation
6. Deployment instructions

Always write complete files — no placeholders, no TODOs.
Use modern best practices: TypeScript, async/await, proper error handling.
Include authentication, validation, and security by default."""


class FullStackAgent(BaseAgent):
    """
    Agent that builds complete full-stack applications.
    Detects the tech stack from the prompt and generates
    the appropriate code for each layer.
    """

    TECH_STACKS = {
        "react_fastapi": {
            "frontend": "React + TypeScript + Tailwind CSS",
            "backend": "FastAPI + SQLAlchemy + PostgreSQL",
            "deploy": "Docker Compose",
        },
        "nextjs_prisma": {
            "frontend": "Next.js 14 + TypeScript",
            "backend": "Next.js API Routes + Prisma",
            "deploy": "Vercel + PlanetScale",
        },
        "vue_django": {
            "frontend": "Vue 3 + Composition API",
            "backend": "Django REST Framework",
            "deploy": "Docker",
        },
        "vanilla": {
            "frontend": "HTML5 + CSS3 + Vanilla JS",
            "backend": "Node.js + Express",
            "deploy": "PM2",
        },
    }

    def handle(self, prompt: str) -> str:
        stack = self._detect_stack(prompt)
        return self._generate_app(prompt, stack)

    def _detect_stack(self, prompt: str) -> str:
        p = prompt.lower()
        if "next" in p or "nextjs" in p:
            return "nextjs_prisma"
        if "vue" in p or "django" in p:
            return "vue_django"
        if "vanilla" in p or "plain" in p or "simple html" in p:
            return "vanilla"
        return "react_fastapi"  # Default modern stack

    def _generate_app(self, prompt: str, stack: str) -> str:
        stack_info = self.TECH_STACKS.get(stack, self.TECH_STACKS["react_fastapi"])

        full_prompt = f"""{FULLSTACK_SYSTEM}

Tech Stack: {stack_info['frontend']} + {stack_info['backend']}
Deployment: {stack_info['deploy']}

User Request: {prompt}

Generate the complete application with all files.
Start with the project structure, then provide each file completely."""

        generated = self._generate(full_prompt, max_tokens=4096, temperature=0.2)
        return self._format_output(generated, stack_info)

    def _format_output(self, generated: str, stack_info: dict) -> str:
        header = f"""
# 🚀 CodeMind Full Stack Generator
# Stack: {stack_info['frontend']} + {stack_info['backend']}
# Deploy: {stack_info['deploy']}
# Generated by CodeMind — Your AI, Your Rules

"""
        return header + generated

    def build_react_fastapi_template(self, app_name: str, features: list) -> dict:
        """
        Generate a complete React + FastAPI application template.
        Returns dict with all file contents.
        """
        files = {}

        # Backend: FastAPI main.py
        files["backend/main.py"] = f'''"""
{app_name} — FastAPI Backend
Generated by CodeMind
"""

from fastapi import FastAPI, Depends, HTTPException, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from sqlalchemy.orm import Session
from typing import List, Optional
import uvicorn

from database import get_db, engine, Base
from models import User, Item
from schemas import UserCreate, UserResponse, ItemCreate, ItemResponse
from auth import create_access_token, verify_token
from routers import users, items

# Create tables
Base.metadata.create_all(bind=engine)

app = FastAPI(
    title="{app_name} API",
    description="Production API generated by CodeMind",
    version="1.0.0",
)

# CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000","http://localhost:5173"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Routers
app.include_router(users.router, prefix="/api/users", tags=["users"])
app.include_router(items.router, prefix="/api/items", tags=["items"])

@app.get("/health")
async def health():
    return {{"status": "ok", "app": "{app_name}", "ai": "CodeMind"}}

if __name__ == "__main__":
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
'''

        # Backend: database.py
        files["backend/database.py"] = '''"""Database configuration with SQLAlchemy"""

from sqlalchemy import create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
import os

DATABASE_URL = os.environ.get(
    "DATABASE_URL",
    "sqlite:///./app.db"
)

engine = create_engine(
    DATABASE_URL,
    connect_args={"check_same_thread": False} if "sqlite" in DATABASE_URL else {},
)

SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()

def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
'''

        # Backend: models.py
        files["backend/models.py"] = f'''"""SQLAlchemy Models"""

from sqlalchemy import Column, Integer, String, Boolean, DateTime, ForeignKey, Text
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from database import Base


class User(Base):
    __tablename__ = "users"
    id = Column(Integer, primary_key=True, index=True)
    email = Column(String, unique=True, index=True, nullable=False)
    username = Column(String, unique=True, index=True, nullable=False)
    hashed_password = Column(String, nullable=False)
    is_active = Column(Boolean, default=True)
    is_admin = Column(Boolean, default=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    items = relationship("Item", back_populates="owner")


class Item(Base):
    __tablename__ = "items"
    id = Column(Integer, primary_key=True, index=True)
    title = Column(String, index=True, nullable=False)
    description = Column(Text, nullable=True)
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    owner_id = Column(Integer, ForeignKey("users.id"))
    owner = relationship("User", back_populates="items")
'''

        # Backend: auth.py
        files["backend/auth.py"] = '''"""JWT Authentication"""

from datetime import datetime, timedelta
from typing import Optional
from jose import JWTError, jwt
from passlib.context import CryptContext
from fastapi import HTTPException, status
import os

SECRET_KEY = os.environ.get("SECRET_KEY", "codemind-super-secret-change-in-production")
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 30

pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")

def verify_password(plain: str, hashed: str) -> bool:
    return pwd_context.verify(plain, hashed)

def hash_password(password: str) -> str:
    return pwd_context.hash(password)

def create_access_token(data: dict, expires_delta: Optional[timedelta] = None) -> str:
    to_encode = data.copy()
    expire = datetime.utcnow() + (expires_delta or timedelta(minutes=ACCESS_TOKEN_EXPIRE_MINUTES))
    to_encode.update({"exp": expire})
    return jwt.encode(to_encode, SECRET_KEY, algorithm=ALGORITHM)

def verify_token(token: str) -> dict:
    try:
        payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
        return payload
    except JWTError:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid token")
'''

        # Frontend: package.json
        files["frontend/package.json"] = json.dumps({
            "name": app_name.lower().replace(" ", "-"),
            "version": "1.0.0",
            "scripts": {
                "dev": "vite",
                "build": "tsc && vite build",
                "preview": "vite preview",
            },
            "dependencies": {
                "react": "^18.2.0",
                "react-dom": "^18.2.0",
                "react-router-dom": "^6.22.0",
                "axios": "^1.6.7",
                "@tanstack/react-query": "^5.28.0",
                "zustand": "^4.5.2",
                "react-hook-form": "^7.51.0",
                "zod": "^3.22.4",
            },
            "devDependencies": {
                "@types/react": "^18.2.66",
                "@vitejs/plugin-react": "^4.2.1",
                "tailwindcss": "^3.4.1",
                "typescript": "^5.2.2",
                "vite": "^5.2.0",
            }
        }, indent=2)

        # Frontend: src/App.tsx
        files["frontend/src/App.tsx"] = f'''import React from "react";
import {{ BrowserRouter as Router, Routes, Route, Navigate }} from "react-router-dom";
import {{ QueryClient, QueryClientProvider }} from "@tanstack/react-query";
import {{ useAuthStore }} from "./store/authStore";
import Home from "./pages/Home";
import Login from "./pages/Login";
import Register from "./pages/Register";
import Dashboard from "./pages/Dashboard";
import Navbar from "./components/Navbar";

const queryClient = new QueryClient({{
  defaultOptions: {{
    queries: {{
      retry: 1,
      staleTime: 30000,
    }},
  }},
}});

const PrivateRoute: React.FC<{{ children: React.ReactNode }}> = ({{ children }}) => {{
  const {{ isAuthenticated }} = useAuthStore();
  return isAuthenticated ? <>{{children}}</> : <Navigate to="/login" />;
}};

export default function App() {{
  return (
    <QueryClientProvider client={{queryClient}}>
      <Router>
        <div className="min-h-screen bg-gray-50">
          <Navbar />
          <Routes>
            <Route path="/" element={{<Home />}} />
            <Route path="/login" element={{<Login />}} />
            <Route path="/register" element={{<Register />}} />
            <Route path="/dashboard" element={{
              <PrivateRoute><Dashboard /></PrivateRoute>
            }} />
          </Routes>
        </div>
      </Router>
    </QueryClientProvider>
  );
}}
'''

        # Frontend: src/store/authStore.ts
        files["frontend/src/store/authStore.ts"] = '''import { create } from "zustand";
import { persist } from "zustand/middleware";
import axios from "axios";

const API = import.meta.env.VITE_API_URL || "http://localhost:8000";

interface AuthState {
  user: any | null;
  token: string | null;
  isAuthenticated: boolean;
  login: (email: string, password: string) => Promise<void>;
  register: (email: string, username: string, password: string) => Promise<void>;
  logout: () => void;
}

export const useAuthStore = create<AuthState>()(
  persist(
    (set) => ({
      user: null,
      token: null,
      isAuthenticated: false,

      login: async (email, password) => {
        const form = new FormData();
        form.append("username", email);
        form.append("password", password);
        const res = await axios.post(`${API}/api/users/login`, form);
        const { access_token, user } = res.data;
        axios.defaults.headers.common["Authorization"] = `Bearer ${access_token}`;
        set({ user, token: access_token, isAuthenticated: true });
      },

      register: async (email, username, password) => {
        await axios.post(`${API}/api/users/register`, { email, username, password });
      },

      logout: () => {
        delete axios.defaults.headers.common["Authorization"];
        set({ user: null, token: null, isAuthenticated: false });
      },
    }),
    { name: "auth-storage" }
  )
);
'''

        # Docker Compose
        files["docker-compose.yml"] = f'''version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/{app_name.lower()}
      - SECRET_KEY=change-this-in-production
    depends_on:
      - db
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: {app_name.lower()}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
'''

        return files

    def save_app(self, files: dict, output_dir: str = "./generated_apps"):
        """Save all generated files to disk."""
        for filepath, content in files.items():
            full_path = os.path.join(output_dir, filepath)
            os.makedirs(os.path.dirname(full_path), exist_ok=True)
            with open(full_path, "w") as f:
                f.write(content)
            print(f"Created: {full_path}")
        print(f"\nApp generated in {output_dir}/")
        print("To run:")
        print("  cd " + output_dir)
        print("  docker-compose up")
