"""
Game Development Agent
Generates complete game code for multiple engines:
- Pygame (Python 2D games)
- Unity C# scripts
- Godot GDScript
- Phaser.js (browser games)
- Terminal/ASCII games
"""

import os
from agents.base_agent import BaseAgent


GAMEDEV_SYSTEM = """You are a senior game developer with expertise in:
- Pygame for Python 2D games
- Unity C# for 3D/2D games
- Godot GDScript for indie games
- Phaser.js for browser games
- ASCII terminal games

When building a game you always provide:
1. Complete game loop (update/render/input)
2. Player controller with smooth movement
3. Collision detection
4. Score system
5. Game states (menu, playing, game over)
6. Sound/music hooks (even if placeholder)
7. Asset loading system
8. Complete runnable code — no placeholders"""


class GameDevAgent(BaseAgent):

    ENGINES = {
        "pygame": ["pygame","python","2d","side","platformer","shooter","snake","tetris","pacman","pong"],
        "unity": ["unity","c#","3d","fps","rpg","unity3d"],
        "godot": ["godot","gdscript","indie"],
        "phaser": ["phaser","browser","web game","html5 game","js game"],
        "terminal": ["terminal","ascii","text","console","cli game"],
    }

    def handle(self, prompt: str) -> str:
        engine = self._detect_engine(prompt)
        return self._generate_game(prompt, engine)

    def _detect_engine(self, prompt: str) -> str:
        p = prompt.lower()
        for engine, keywords in self.ENGINES.items():
            if any(k in p for k in keywords):
                return engine
        return "pygame"

    def _generate_game(self, prompt: str, engine: str) -> str:
        system = GAMEDEV_SYSTEM

        if engine == "pygame":
            return self._generate_pygame(prompt)
        elif engine == "unity":
            return self._generate_unity(prompt)
        elif engine == "godot":
            return self._generate_godot(prompt)
        elif engine == "phaser":
            return self._generate_phaser(prompt)
        elif engine == "terminal":
            return self._generate_terminal(prompt)

        full_prompt = f"{system}\n\nEngine: {engine}\nGame Request: {prompt}\n\nGenerate complete game code:"
        return self._generate(full_prompt, max_tokens=4096, temperature=0.3)

    def _generate_pygame(self, prompt: str) -> str:
        base_game = '''#!/usr/bin/env python3
"""
Game generated by CodeMind
Install: pip install pygame
Run: python game.py
"""

import pygame
import sys
import random
import math
from enum import Enum
from dataclasses import dataclass
from typing import List, Optional, Tuple


# ============================================================
# CONSTANTS
# ============================================================
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
FPS = 60
TITLE = "CodeMind Game"

# Colors
BLACK    = (0,   0,   0)
WHITE    = (255, 255, 255)
RED      = (220, 50,  50)
GREEN    = (50,  200, 50)
BLUE     = (50,  100, 220)
YELLOW   = (255, 220, 0)
PURPLE   = (150, 50,  220)
CYAN     = (0,   220, 220)
ORANGE   = (255, 140, 0)
GRAY     = (128, 128, 128)
DARK     = (20,  20,  30)


class GameState(Enum):
    MENU = "menu"
    PLAYING = "playing"
    PAUSED = "paused"
    GAME_OVER = "game_over"
    WIN = "win"


@dataclass
class Vector2:
    x: float = 0.0
    y: float = 0.0

    def __add__(self, other):
        return Vector2(self.x + other.x, self.y + other.y)

    def length(self) -> float:
        return math.sqrt(self.x**2 + self.y**2)

    def normalize(self):
        l = self.length()
        if l > 0:
            return Vector2(self.x/l, self.y/l)
        return Vector2()


class SoundManager:
    """Handles all game audio. Replace with actual sound files."""
    def __init__(self):
        self.enabled = True
        try:
            pygame.mixer.init()
        except Exception:
            self.enabled = False

    def play_jump(self): pass
    def play_collect(self): pass
    def play_hit(self): pass
    def play_death(self): pass
    def play_win(self): pass


class Particle:
    """Visual particle effect."""
    def __init__(self, x, y, color, vel_x=0, vel_y=0, lifetime=30):
        self.pos = Vector2(x, y)
        self.vel = Vector2(vel_x + random.uniform(-2,2), vel_y + random.uniform(-3,0))
        self.color = color
        self.lifetime = lifetime
        self.max_lifetime = lifetime
        self.size = random.randint(2, 6)

    def update(self):
        self.pos.x += self.vel.x
        self.pos.y += self.vel.y
        self.vel.y += 0.2  # gravity
        self.lifetime -= 1

    def draw(self, surface):
        alpha = self.lifetime / self.max_lifetime
        size = max(1, int(self.size * alpha))
        color = tuple(int(c * alpha) for c in self.color)
        pygame.draw.circle(surface, color, (int(self.pos.x), int(self.pos.y)), size)

    @property
    def dead(self): return self.lifetime <= 0


class Player(pygame.sprite.Sprite):
    """Player character with full movement, animation, and physics."""

    SPEED = 5
    JUMP_FORCE = -15
    GRAVITY = 0.8
    MAX_FALL_SPEED = 20

    def __init__(self, x: float, y: float):
        super().__init__()
        self.pos = Vector2(x, y)
        self.vel = Vector2()
        self.on_ground = False
        self.health = 3
        self.max_health = 3
        self.score = 0
        self.invincible_timer = 0
        self.facing_right = True

        # Sprite
        self.image = pygame.Surface((40, 50), pygame.SRCALPHA)
        self._draw_player_sprite()
        self.rect = self.image.get_rect(topleft=(x, y))

        # Animation
        self.anim_frame = 0
        self.anim_timer = 0

    def _draw_player_sprite(self):
        """Draw the player character."""
        self.image.fill((0,0,0,0))
        # Body
        pygame.draw.rect(self.image, BLUE, (5, 15, 30, 30), border_radius=5)
        # Head
        pygame.draw.circle(self.image, (255,220,180), (20, 12), 12)
        # Eyes
        pygame.draw.circle(self.image, BLACK, (24, 10), 3)
        pygame.draw.circle(self.image, WHITE, (25, 9), 1)
        # Legs
        pygame.draw.rect(self.image, BLUE, (8, 42, 10, 8), border_radius=3)
        pygame.draw.rect(self.image, BLUE, (22, 42, 10, 8), border_radius=3)

    def handle_input(self, keys):
        """Process keyboard/gamepad input."""
        self.vel.x = 0
        if keys[pygame.K_LEFT] or keys[pygame.K_a]:
            self.vel.x = -self.SPEED
            self.facing_right = False
        if keys[pygame.K_RIGHT] or keys[pygame.K_d]:
            self.vel.x = self.SPEED
            self.facing_right = True
        if (keys[pygame.K_SPACE] or keys[pygame.K_UP] or keys[pygame.K_w]) and self.on_ground:
            self.vel.y = self.JUMP_FORCE
            self.on_ground = False

    def apply_gravity(self):
        self.vel.y = min(self.vel.y + self.GRAVITY, self.MAX_FALL_SPEED)

    def update(self, platforms, enemies, collectibles, particles):
        # Physics
        self.apply_gravity()
        self.pos.x += self.vel.x
        self.rect.x = int(self.pos.x)
        self._handle_platform_collision_x(platforms)
        self.pos.y += self.vel.y
        self.rect.y = int(self.pos.y)
        self.on_ground = False
        self._handle_platform_collision_y(platforms)

        # Boundaries
        if self.rect.left < 0:
            self.rect.left = 0
            self.pos.x = 0
        if self.rect.right > SCREEN_WIDTH:
            self.rect.right = SCREEN_WIDTH
            self.pos.x = SCREEN_WIDTH - self.rect.width

        # Invincibility
        if self.invincible_timer > 0:
            self.invincible_timer -= 1

        # Collect items
        for item in collectibles[:]:
            if self.rect.colliderect(item.rect):
                self.score += item.value
                for _ in range(8):
                    particles.append(Particle(item.rect.centerx, item.rect.centery, YELLOW, lifetime=20))
                collectibles.remove(item)

        # Enemy collision
        if self.invincible_timer == 0:
            for enemy in enemies:
                if self.rect.colliderect(enemy.rect):
                    if self.vel.y > 0 and self.rect.bottom < enemy.rect.centery + 10:
                        # Stomp enemy
                        enemy.die()
                        self.vel.y = self.JUMP_FORCE * 0.7
                        self.score += 100
                        for _ in range(10):
                            particles.append(Particle(enemy.rect.centerx, enemy.rect.centery, RED))
                    else:
                        self.take_damage(particles)

    def _handle_platform_collision_x(self, platforms):
        for p in platforms:
            if self.rect.colliderect(p.rect):
                if self.vel.x > 0:
                    self.rect.right = p.rect.left
                elif self.vel.x < 0:
                    self.rect.left = p.rect.right
                self.pos.x = float(self.rect.x)
                self.vel.x = 0

    def _handle_platform_collision_y(self, platforms):
        for p in platforms:
            if self.rect.colliderect(p.rect):
                if self.vel.y > 0:
                    self.rect.bottom = p.rect.top
                    self.on_ground = True
                elif self.vel.y < 0:
                    self.rect.top = p.rect.bottom
                self.pos.y = float(self.rect.y)
                self.vel.y = 0

    def take_damage(self, particles):
        self.health -= 1
        self.invincible_timer = 90
        for _ in range(15):
            particles.append(Particle(self.rect.centerx, self.rect.centery, RED))

    def draw(self, surface):
        if self.invincible_timer > 0 and self.invincible_timer % 6 < 3:
            return
        sprite = self.image
        if not self.facing_right:
            sprite = pygame.transform.flip(sprite, True, False)
        surface.blit(sprite, self.rect)

    def draw_hud(self, surface):
        # Health hearts
        for i in range(self.max_health):
            color = RED if i < self.health else GRAY
            pygame.draw.polygon(surface, color, [
                (20 + i*35, 25), (14 + i*35, 17), (8 + i*35, 22),
                (8 + i*35, 28), (20 + i*35, 38), (32 + i*35, 28),
                (32 + i*35, 22), (26 + i*35, 17)
            ])
        # Score
        font = pygame.font.Font(None, 36)
        score_text = font.render(f"Score: {self.score}", True, WHITE)
        surface.blit(score_text, (SCREEN_WIDTH - 180, 10))


class Platform(pygame.sprite.Sprite):
    def __init__(self, x, y, w, h, color=None):
        super().__init__()
        self.rect = pygame.Rect(x, y, w, h)
        self.color = color or (80, 60, 40)
        self.image = pygame.Surface((w, h))
        self._draw()

    def _draw(self):
        self.image.fill(self.color)
        # Top highlight
        pygame.draw.rect(self.image, tuple(min(255,c+40) for c in self.color), (0,0,self.rect.width,6))
        # Bottom shadow
        pygame.draw.rect(self.image, tuple(max(0,c-40) for c in self.color), (0,self.rect.height-4,self.rect.width,4))

    def draw(self, surface):
        surface.blit(self.image, self.rect)


class Enemy(pygame.sprite.Sprite):
    def __init__(self, x, y, patrol_range=100):
        super().__init__()
        self.rect = pygame.Rect(x, y, 36, 36)
        self.pos = Vector2(x, y)
        self.vel = Vector2(2, 0)
        self.start_x = x
        self.patrol_range = patrol_range
        self.alive = True

    def update(self):
        if not self.alive:
            return
        self.pos.x += self.vel.x
        self.rect.x = int(self.pos.x)
        if abs(self.pos.x - self.start_x) > self.patrol_range:
            self.vel.x *= -1

    def die(self):
        self.alive = False
        self.kill()

    def draw(self, surface):
        if not self.alive:
            return
        # Body
        pygame.draw.rect(surface, RED, self.rect, border_radius=6)
        # Eyes
        ex = self.rect.x
        ey = self.rect.y
        pygame.draw.circle(surface, WHITE, (ex+10, ey+12), 6)
        pygame.draw.circle(surface, WHITE, (ex+26, ey+12), 6)
        pygame.draw.circle(surface, BLACK, (ex+11, ey+12), 3)
        pygame.draw.circle(surface, BLACK, (ex+27, ey+12), 3)
        # Mouth
        pygame.draw.arc(surface, BLACK, (ex+8, ey+20, 20, 10), 3.14, 0, 2)


class Collectible(pygame.sprite.Sprite):
    def __init__(self, x, y, value=10, color=YELLOW):
        super().__init__()
        self.rect = pygame.Rect(x, y, 20, 20)
        self.value = value
        self.color = color
        self.float_offset = random.uniform(0, 6.28)
        self.float_timer = 0

    def update(self):
        self.float_timer += 0.05
        self.rect.y = int(self.rect.y + math.sin(self.float_timer + self.float_offset) * 0.3)

    def draw(self, surface):
        pygame.draw.circle(surface, self.color, self.rect.center, 10)
        pygame.draw.circle(surface, WHITE, (self.rect.centerx-3, self.rect.centery-3), 3)


def create_level_1() -> Tuple[List[Platform], List[Enemy], List[Collectible]]:
    platforms = [
        # Ground
        Platform(0, SCREEN_HEIGHT-40, SCREEN_WIDTH, 40),
        # Platforms
        Platform(100, 450, 150, 20),
        Platform(300, 380, 180, 20),
        Platform(520, 300, 140, 20),
        Platform(200, 220, 200, 20),
        Platform(450, 160, 160, 20),
        Platform(650, 230, 130, 20),
        # Moving challenge
        Platform(50, 330, 80, 20),
        Platform(700, 400, 80, 20),
    ]
    enemies = [
        Enemy(350, 340, 100),
        Enemy(530, 260, 80),
        Enemy(220, 180, 120),
    ]
    collectibles = [
        Collectible(130, 420, 10),
        Collectible(360, 350, 10),
        Collectible(250, 190, 20, CYAN),
        Collectible(470, 130, 20, CYAN),
        Collectible(680, 200, 50, ORANGE),
    ]
    return platforms, enemies, collectibles


class Game:
    """Main game class with full game loop."""

    def __init__(self):
        pygame.init()
        self.screen = pygame.display.set_mode((SCREEN_WIDTH, SCREEN_HEIGHT))
        pygame.display.set_caption(TITLE)
        self.clock = pygame.time.Clock()
        self.state = GameState.MENU
        self.font_large = pygame.font.Font(None, 72)
        self.font_med = pygame.font.Font(None, 42)
        self.font_small = pygame.font.Font(None, 28)
        self.sound = SoundManager()
        self.particles: List[Particle] = []
        self._reset()

    def _reset(self):
        self.player = Player(100, 500)
        self.platforms, self.enemies, self.collectibles = create_level_1()
        self.particles.clear()

    def handle_events(self):
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit()
                sys.exit()
            if event.type == pygame.KEYDOWN:
                if event.key == pygame.K_ESCAPE:
                    if self.state == GameState.PLAYING:
                        self.state = GameState.PAUSED
                    elif self.state == GameState.PAUSED:
                        self.state = GameState.PLAYING
                if event.key == pygame.K_RETURN:
                    if self.state in (GameState.MENU, GameState.GAME_OVER, GameState.WIN):
                        self._reset()
                        self.state = GameState.PLAYING

    def update(self):
        if self.state != GameState.PLAYING:
            return
        keys = pygame.key.get_pressed()
        self.player.handle_input(keys)
        self.player.update(self.platforms, self.enemies, self.collectibles, self.particles)
        for e in self.enemies[:]:
            e.update()
            if not e.alive:
                self.enemies.remove(e)
        for c in self.collectibles:
            c.update()
        for p in self.particles[:]:
            p.update()
            if p.dead:
                self.particles.remove(p)
        # Check death
        if self.player.health <= 0 or self.player.rect.top > SCREEN_HEIGHT + 50:
            self.state = GameState.GAME_OVER
        # Check win
        if not self.collectibles and not self.enemies:
            self.state = GameState.WIN

    def draw(self):
        self.screen.fill(DARK)
        # Background stars
        for i in range(0, SCREEN_WIDTH, 80):
            for j in range(0, SCREEN_HEIGHT, 80):
                pygame.draw.circle(self.screen, (50,50,70), (i + (j*7)%80, j + (i*3)%80), 1)

        if self.state == GameState.MENU:
            self._draw_menu()
        elif self.state in (GameState.PLAYING, GameState.PAUSED):
            self._draw_game()
            if self.state == GameState.PAUSED:
                self._draw_pause()
        elif self.state == GameState.GAME_OVER:
            self._draw_game()
            self._draw_game_over()
        elif self.state == GameState.WIN:
            self._draw_game()
            self._draw_win()

        pygame.display.flip()

    def _draw_game(self):
        for p in self.platforms:
            p.draw(self.screen)
        for c in self.collectibles:
            c.draw(self.screen)
        for e in self.enemies:
            e.draw(self.screen)
        for p in self.particles:
            p.draw(self.screen)
        self.player.draw(self.screen)
        self.player.draw_hud(self.screen)

    def _draw_menu(self):
        t = self.font_large.render(TITLE, True, CYAN)
        self.screen.blit(t, t.get_rect(center=(SCREEN_WIDTH//2, 180)))
        sub = self.font_med.render("Generated by 👑 CodeMind AI", True, YELLOW)
        self.screen.blit(sub, sub.get_rect(center=(SCREEN_WIDTH//2, 260)))
        inst = [
            "ARROW KEYS / WASD — Move",
            "SPACE / W / UP — Jump",
            "Stomp enemies from above!",
            "Collect all items to win!",
            "",
            "ENTER — Start",
        ]
        for i, line in enumerate(inst):
            color = GREEN if "ENTER" in line else WHITE
            t = self.font_small.render(line, True, color)
            self.screen.blit(t, t.get_rect(center=(SCREEN_WIDTH//2, 340+i*32)))

    def _draw_game_over(self):
        overlay = pygame.Surface((SCREEN_WIDTH, SCREEN_HEIGHT), pygame.SRCALPHA)
        overlay.fill((0,0,0,160))
        self.screen.blit(overlay, (0,0))
        t = self.font_large.render("GAME OVER", True, RED)
        self.screen.blit(t, t.get_rect(center=(SCREEN_WIDTH//2, 220)))
        s = self.font_med.render(f"Score: {self.player.score}", True, WHITE)
        self.screen.blit(s, s.get_rect(center=(SCREEN_WIDTH//2, 310)))
        r = self.font_small.render("ENTER — Retry", True, YELLOW)
        self.screen.blit(r, r.get_rect(center=(SCREEN_WIDTH//2, 380)))

    def _draw_win(self):
        overlay = pygame.Surface((SCREEN_WIDTH, SCREEN_HEIGHT), pygame.SRCALPHA)
        overlay.fill((0,20,0,160))
        self.screen.blit(overlay, (0,0))
        t = self.font_large.render("YOU WIN!", True, YELLOW)
        self.screen.blit(t, t.get_rect(center=(SCREEN_WIDTH//2, 220)))
        s = self.font_med.render(f"Final Score: {self.player.score}", True, WHITE)
        self.screen.blit(s, s.get_rect(center=(SCREEN_WIDTH//2, 310)))
        r = self.font_small.render("ENTER — Play Again", True, GREEN)
        self.screen.blit(r, r.get_rect(center=(SCREEN_WIDTH//2, 380)))

    def _draw_pause(self):
        overlay = pygame.Surface((SCREEN_WIDTH, SCREEN_HEIGHT), pygame.SRCALPHA)
        overlay.fill((0,0,0,120))
        self.screen.blit(overlay, (0,0))
        t = self.font_large.render("PAUSED", True, WHITE)
        self.screen.blit(t, t.get_rect(center=(SCREEN_WIDTH//2, 280)))
        r = self.font_small.render("ESC — Resume", True, GRAY)
        self.screen.blit(r, r.get_rect(center=(SCREEN_WIDTH//2, 360)))

    def run(self):
        print(f"Starting {TITLE} — Generated by CodeMind AI")
        while True:
            self.handle_events()
            self.update()
            self.draw()
            self.clock.tick(FPS)


if __name__ == "__main__":
    Game().run()
'''

        # Save the game
        os.makedirs("./generated_games", exist_ok=True)
        game_path = "./generated_games/pygame_game.py"
        with open(game_path, "w") as f:
            f.write(base_game)

        enhanced = self._generate(
            f"{GAMEDEV_SYSTEM}\n\nBase game structure provided. Now customize it for this request:\n{prompt}\n\nProvide additional game features, mechanics, or modifications:",
            max_tokens=2048,
            temperature=0.4,
        )

        return f"""# 🎮 Game Generated by CodeMind!
# Install: pip install pygame
# Run: python generated_games/pygame_game.py

## Base Game Saved To: generated_games/pygame_game.py

## AI-Generated Customizations For Your Request:
{enhanced}

## Controls:
- Arrow Keys / WASD — Move
- Space / W / Up — Jump
- Stomp enemies from above
- Collect all items to win
- ESC — Pause
- ENTER — Start/Restart
"""

    def _generate_unity(self, prompt: str) -> str:
        unity_code = self._generate(
            f"{GAMEDEV_SYSTEM}\n\nEngine: Unity C#\nRequest: {prompt}\n\nGenerate complete Unity C# scripts:",
            max_tokens=3072, temperature=0.3
        )
        return f"# Unity C# Game Scripts\n# Generated by CodeMind\n\n{unity_code}"

    def _generate_godot(self, prompt: str) -> str:
        godot_code = self._generate(
            f"{GAMEDEV_SYSTEM}\n\nEngine: Godot GDScript\nRequest: {prompt}\n\nGenerate complete GDScript:",
            max_tokens=3072, temperature=0.3
        )
        return f"# Godot GDScript Game\n# Generated by CodeMind\n\n{godot_code}"

    def _generate_phaser(self, prompt: str) -> str:
        phaser_code = self._generate(
            f"{GAMEDEV_SYSTEM}\n\nEngine: Phaser 3 (JavaScript)\nRequest: {prompt}\n\nGenerate complete HTML+JS game:",
            max_tokens=3072, temperature=0.3
        )
        return f"<!-- Phaser.js Game — Generated by CodeMind -->\n{phaser_code}"

    def _generate_terminal(self, prompt: str) -> str:
        terminal_code = self._generate(
            f"{GAMEDEV_SYSTEM}\n\nType: Terminal/ASCII Python game\nRequest: {prompt}\n\nGenerate complete terminal game:",
            max_tokens=3072, temperature=0.3
        )
        return f"# Terminal Game — Generated by CodeMind\n{terminal_code}"
